# Generated by Django 5.0.13 on 2025-12-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoHotel',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HabitacionHotel',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10)),
                ('tipo_habitacion', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_habitacion', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField()),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('dni_pasaporte', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField()),
                ('categoria', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('numero_adultos', models.IntegerField()),
                ('numero_ninos', models.IntegerField()),
                ('estado_reserva', models.CharField(max_length=50)),
                ('total_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateTimeField()),
                ('id_huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaHotel',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('id_huesped_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.huesped')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservahotel')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id_detalle_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('precio_noche_reservado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_noches', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_adicionales', models.TextField()),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacionhotel')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservahotel')),
            ],
        ),
    ]
