# Generated by Django 5.0.13 on 2025-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacionhotel',
            name='tipo_habitacion',
            field=models.CharField(choices=[('basica', 'Básica'), ('premium', 'Premium'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('presidencial', 'Presidencial')], max_length=50),
        ),
    ]
