# Generated by Django 5.0.13 on 2025-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_habitacionhotel_tipo_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacionhotel',
            name='estado_habitacion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En limpieza'), ('mantenimiento', 'En mantenimiento'), ('reservada', 'Reservada')], max_length=50),
        ),
    ]
