# Generated by Django 5.0.13 on 2025-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_habitacionhotel_estado_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadohotel',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('recepcionista', 'Recepcionista'), ('limpieza', 'Personal de Limpieza'), ('mantenimiento', 'Personal de Mantenimiento'), ('botones', 'Botones')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facturahotel',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facturahotel',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='estado_reserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicioadicional',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('spa', 'Spa'), ('transporte', 'Transporte'), ('lavanderia', 'Lavandería')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicioadicional',
            name='disponible',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='servicioadicional',
            name='duracion',
            field=models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Por día'), ('evento', 'Por evento')], max_length=50),
        ),
    ]
