# Generated by Django 5.0.13 on 2025-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_empleadohotel_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='servicios_adicionales',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='servicios_adicionales',
            field=models.ManyToManyField(blank=True, to='hotel.servicioadicional'),
        ),
    ]
